### ISSUE TITLE
Add side nav to cp & interns

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#346]
Side navigation is needed for the list page of career possibilities and interns..
https://staging.ansc.illinois.edu/future-students/career-possibilities
https://staging.ansc.illinois.edu/student-life/internships

Side nav is also needed on each profile page.
https://staging.ansc.illinois.edu/future-students/career-possibilities/christina-mazulis-dvm-dacvd
https://staging.ansc.illinois.edu/student-life/internships/university-illinois-swine-research-center

**Comment by wrg20** [comment]
ok I created a new paragraph type that allows for inserting blocks from the views.  So we can insert the career possibilities block into a regular page now.  The user will use the block reference paragraph type and choose the block they want to insert with the sidebar.  The block has to be first placed in the "hidden" region of the theme.  The hidden region activates the block but does not get displayed because the region isn't programmed into any of the templates.

**Comment by mwllr** [comment]
moved to ACES theme repository.
