### ISSUE TITLE
Add Mediaspace support to video embed

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#406]
The LAS framework includes some code to add support for embedding mediaspace video into text content are.  Not sure if the same code could be used for adding to the media library, but it should be explored.

**Comment by nbaxley-uiuc** [comment]
The LAS implementation will not work since we are NOT using MediaLibrary for our video.  MediaSpace is powered by Kaltura and there is a Kaltura plugin we can use. - https://www.drupal.org/project/media_kaltura

**Comment by nbaxley-uiuc** [comment]
This is used specifically in the Feature Video paragraph type.

**Comment by trubach** [comment]
Here's an article about adding oEmbed sources to the media library, in case Media Space adds oEmbed support in the future

https://www.hashbangcode.com/article/drupal-9-using-and-adding-oembed-providers

**Comment by robgasc** [comment]
I've created two pull requests: https://github.com/web-illinois/illinois_framework_core/pull/65 and https://github.com/web-illinois/illinois_framework_profile/pull/22 which together enable the video embed field module, and video embed wysiwyg module. The module that was a separate entity in the las framework is moved into the core, since it is a single file that adds the additional provider. Before we merge, just want to outline how this process should work.

All you need now to embed the mediaspace videos is the url, dropping that link directly into that new video button on the basic html editor, and then it should pull down.

Obviously, for future reference, migrating directly to the entity style of media in core for mediaspace (a future project IF tech services gets oembed renabled.) will be a challenge, since these items are only text in the editor.

**Comment by mwllr** [comment]
@robgasc - where are we at on this one??

**Comment by robgasc** [comment]
@mwllr This should be merged and good to go. There is another couple pull requests that add mediaspace videos to the media library now as well. That could be in 2.2. I'm not sure why this ticket is still open so I'll go ahead and close it.
