### ISSUE TITLE
Image alignment in rich text areas not working correctly.

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#411]
need images to be able to float left or right in drop down for ck editor, not as a class applied.

**Comment by nbaxley-uiuc** [comment]
Currently there's an option to specify left/right/center/none for image alignment, but in practice it only aligns the first line of text.

**Comment by nbaxley-uiuc** [comment]
Related to #459

**Comment by nbaxley-uiuc** [comment]
For example.  In the screenshot below, the images is supposed to be right aligned to the text with the text flowing around it.  The preview in the editor shows correctly.  The screenshot is from http://mcb.web.illinois.edu/academics/graduate-studies.

![image](https://user-images.githubusercontent.com/62560479/140990882-f923c682-bea8-4edc-a0a6-6339554ea020.png)

**Comment by magjarvis** [comment]
I may need some help with this one: @wrg20 @trubach @robgasc 

It looks like this might have something to do with the sidebar? The issue is the align-right/align-left/align-center classes aren't being applied to the image. However, they ARE being applied in the News CT. Also, they are being applied in the body when the sidebar is disabled
<img width="557" alt="Screenshot 2021-12-01 131949" src="https://user-images.githubusercontent.com/8452264/144300322-262b0ffb-20f4-49c3-a387-6c87be89a3f0.png">
<img width="593" alt="Screenshot 2021-12-01 132014" src="https://user-images.githubusercontent.com/8452264/144300345-417a6bf3-7303-4950-9347-e2f487d1ebee.png">
<img width="554" alt="Screenshot 2021-12-01 132038" src="https://user-images.githubusercontent.com/8452264/144300813-1a8b3568-06fe-4ba6-bf6b-3e285ade9eb5.png">
HOWEVER, the classes are NOT applied in the rich text paragraph no matter whether the sidebar is enabled


I'm stumped, is there anything in the sidebar config that may be overriding or blocking these classes from being applied?
<img width="544" alt="Screenshot 2021-12-01 133028" src="https://user-images.githubusercontent.com/8452264/144302213-5182a6eb-7e96-4afb-b5cf-00d02a30a5f2.png">

**Comment by trubach** [comment]
It looks like the left-align image is working, but not the center or right-align. See https://illinois-drupal.web.illinois.edu/image-alignment-test

**Comment by magjarvis** [comment]
I think it's something to do with the paragraphs template. Right-align works in the body field, but not in the rich text paragraph. I've added a demo to that test page

**Comment by mwllr** [comment]
https://illinois-drupal.web.illinois.edu/paragraphs/rich-text/rich-text-images

**Comment by nbaxley-uiuc** [comment]
I think this is related to #605

**Comment by nbaxley-uiuc** [comment]
Testing here all looks good.  https://illinois-drupal.web.illinois.edu/paragraphs/rich-text/rich-text-images
