### ISSUE TITLE
News - Archive page config

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#415]
- [x] change thumbnail to square thumbnail, add new image style
- [x] change sort order to sort by date field instead of created date
- [x] Create a block version of this view as described in the [comment below](https://github.com/web-illinois/illinois_framework_theme/issues/415#issuecomment-928184050)

**Comment by nbaxley-uiuc** [comment]
I concur that the thumbnail images should be squares.

**Comment by nbaxley-uiuc** [comment]
There is concern that the view-page will cause confusion when a site wants to do something different with the /news/ page.  In order to have _something_ there for sites with minimal effort, we can leave it there but we need to have a block version of this view available for people to use when they don't want to have the the standard page listing.  We can document that the best way to handle this is to disable view-page and then embed the view-block into a Content Page.

**Comment by mwllr** [comment]
We believe this is done. Created a new issue for documentation. Still may need template file/css.
@nbaxley-uiuc
