### ISSUE TITLE
Add functionality for Rich Text video embeds

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#442]
This requires several contrib modules centered around [this one](https://www.drupal.org/project/video_embed_field).  There is a note that this module should no longer be needed with the new media library in core, but we are going to use it for now so that we have ckeditor integration and MediaSpace support.

**Comment by nbaxley-uiuc** [comment]
Related to #459

**Comment by robgasc** [comment]
I've created two pull requests: [web-illinois/illinois_framework_core#65](https://github.com/web-illinois/illinois_framework_core/pull/65) and [web-illinois/illinois_framework_profile#22](https://github.com/web-illinois/illinois_framework_profile/pull/22) which together enable the video embed field module, and video embed wysiwyg module. The module that was a separate entity in the las framework is moved into the core, since it is a single file that adds the additional provider. Before we merge, just want to outline how this process should work.

All you need now to embed the mediaspace videos is the url, dropping that link directly into that new video button on the basic html editor, and then it should pull down.

Obviously, for future reference, migrating directly to the entity style of media in core for mediaspace (a future project IF tech services gets oembed renabled.) will be a challenge, since these items are only text in the editor.
