### ISSUE TITLE
Fix il-blue buttons on hero

### ISSUE THREAD

**Issue by wrg20** [ATLAS-Illinois/Illinois-Framework-Theme#489]
![image](https://user-images.githubusercontent.com/1544079/138914330-fe478aaa-f7ae-4111-8565-c3fea64b629e.png)

The illinois framework button code is interfering with the toolkit button code.

**Comment by robgasc** [comment]
I knew I should have added a note here too; this a problem with the overrides on the il-blue style; it only shows the text white when the link is visited. I initially thought it was something with the toolkit, but it looks like we do a local override.

I believe the culprit is 
```
a.il-button.il-blue {
    color: var(--il-blue) !important;
}
```
in _web-components.buttons.scss. Color should be white. Not sure what color visited should be then, as visited links show white text.

**Comment by wrg20** [comment]
Merge #508 should fix this

**Comment by wrg20** [comment]
Need to remove the .btn class
![image](https://user-images.githubusercontent.com/1544079/139378714-45135761-17e3-4d3e-83c7-3cade9a8a135.png)
