### ISSUE TITLE
News archive PAGE formatting

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#539]
The title is in the correct location, but there is extra space to the left of the content. When the news listing page is full screen (no sidebar) there seems to be more, but there is still some when there is a sidebar as well. Full screen Example here Sidebar example here

**Comment by magjarvis** [comment]
Check with @mwllr on this. On full screen, I set up the content to only be 900px wide to follow with the rich text and paragraph standards for blocks of text. That's why there is extra space on both sides. 

With the sidebar news, it looks like we'll just need to override the padding that's getting inherited from the .fixed-width class

**Comment by nbaxley-uiuc** [comment]
I just talked with @mwllr and we can remove ANY of the 900px width limitations.
