### ISSUE TITLE
Ensure that Highlighted News blocks are contained in the page width

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#671]
There's an example of this [failing here](https://drupal.webtheme.illinois.edu/highlighted-news).  Any solution should apply wherever the highlighted news block is used.  Ideally it would apply to all views content.

**Comment by nbaxley-uiuc** [comment]
I think the solution here is to add the "fixed-width" class to one of the containers, but not sure at what level makes the most sense.  As an initial approach, can anyone see an issue just applying the class to every view block?  It looks like adding it to the initial div in the block.html.twig file would work but I'm open to someone telling me why not.  Putting it there would also fix the block titles being aligned incorrectly. @wrg20 ?

**Comment by wrg20** [comment]
@nbaxley-uiuc - it's possible that we create a full width block for something so putting it on the block.html.twig may not be the best place...however we could put it on something like block--news.html.twig (insert custom block name for view/block layout).  In your example it would be a template based off of block-views-blocknews-block-2.  Unless we agree that the default should be a constrained width and we only want to override the width if that changes.  I'd have to see if we have any blocks that would be affected by changing to fixed-width.

**Comment by wrg20** [comment]
@mwllr - It may be worthwhile to create a custom blocks/blocks section to the illinois drupal (https://drupal.webtheme.illinois.edu) website.  So we can see the block behavior of all of our views blocks / custom blocks.

**Comment by robgasc** [comment]
https://github.com/web-illinois/illinois_framework_core/pull/80 adds fixed width to the config for the highlighted block. I know there is a broader discussion going on in this thread about *where* and *when* we should default to full-width, but since the initial scope was to make the highlighted news block stay in the fixed-width region, this pull request should close this. If it is a still relevant discussion, a new issue would be cool.
