### ISSUE TITLE
Cards paragraph type

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Theme#74]
Cards paragraph type. 2-3 items per row. White and blue background options

**Comment by wrg20** [comment]
@magjarvis - is this what you were talking about with the buttons aligning at the bottom? 
![image](https://user-images.githubusercontent.com/1544079/119596493-e50c3200-bda4-11eb-92cd-952e1705ba3f.png)

**Comment by wrg20** [comment]
@magjarvis - try this and let me know if it works.
![image](https://user-images.githubusercontent.com/1544079/119599912-8d24f980-bdab-11eb-9ca6-1c2444a8fd79.png)

![image](https://user-images.githubusercontent.com/1544079/119599797-50f19900-bdab-11eb-806e-2ac323992544.png)

**Comment by wrg20** [comment]
@melissa - are images optional on the cards or are they required?

**Comment by mwllr** [comment]
Add field for spacing before paragraph: no, small, med, lg, xlg..
See Call to Action Narrow for example already added.

**Comment by magjarvis** [comment]
Margin should be added to cards already, but let me know if I need to re-push the branch

**Comment by mwllr** [comment]
- [x] Title and subtitle should be centered since the cards are always centered.
- [ ] page layout - once we are above 992, cards can go out to 1600 pixels wide with 4 cards. keep the minimum 50px margin on both sides.  (same as clickable cards)
![Screen Shot 2021-06-24 at 1 11 11 PM](https://user-images.githubusercontent.com/54747669/123312270-b7bebb00-d4ed-11eb-9a41-3e4cc5e26b3b.png)
- [x] tighten up spacing inside box. Change font sizes and line height to be closer to:
![Screen Shot 2021-06-24 at 1 20 51 PM](https://user-images.githubusercontent.com/54747669/123313406-205a6780-d4ef-11eb-86c1-89467ca64db1.png)

**Comment by magjarvis** [comment]
@mwllr right now there is the option to choose between left or center aligned for the title. Are we getting rid of that option and just center-aligning the header/subhead by default?

**Comment by magjarvis** [comment]
@mwllr also, cards are currently limited to 3 per row, should I expand that to allow users to create an unlimited amount of cards that will wrap as they fill the space?

**Comment by magjarvis** [comment]
Pushed to git:

Config changes
- Changed from limited to unlimited
- Removed layout option
CSS changes
- fixed spacing issues within cards content
- title and subtitle are now centered by default
