### ISSUE TITLE
Update the Bootstrap version in style.scss (4.5.3 to 4.6.1) - may be needed after composer updates

### ISSUE THREAD

**Issue by amyliles** [ATLAS-Illinois/Illinois-Framework-Theme#778]
Hi there,

When running updates, an error came up today in style.scss due to a hard-coded version of Bootstrap being referenced.  Composer is updating Bootstrap, but the hard-coded file path is not updated along with Bootstrap, which causes the site to throw errors and break.

File;
https://github.com/web-illinois/illinois_framework_theme/blob/2.x/scss/style.scss

Line 4 - throws an error after composer updates:
@import '../../../../themes/contrib/bootstrap4/dist/bootstrap/4.5.3/scss/bootstrap';

Current solution:
Change line 4 to:
@import '../../../../themes/contrib/bootstrap4/dist/bootstrap/4.6.1/scss/bootstrap';

And run drush commands again to get working.

Is there maybe a way change this line to be more version agnostic, or somehow drop it altogether (if the Bootstrap4 theme is already installed), in a way that might avoid this issue, looking down the road?  

Alternatively, a different option might be to set a specific locked version of the Bootstrap4 theme in Composer.json for the Illinois Framework and then just use that to be sure everyone is always using the same version of Bootstrap.  

I've tested the line 4 solution above and it works, but have not looked at other fixes to the more general Bootstrap4 issue as yet.

Thanks!

_Amy

**Comment by wrg20** [comment]
We haven’t upgraded to the new version of Bootstrap yet so that is on our list of things to do and test to make sure nothing breaks (looks like it broke).  Currently we have hardcoded the version into the framework.  We have also talked about removing bootstrap entirely and only keeping the parts we really need like the grid framework.

**Comment by trubach** [comment]
Thanks for bringing this up, Amy. This has been on my radar for a bit. 

We do have the version of Bootstrap4 set in the [theme's composer file](https://github.com/web-illinois/illinois_framework_theme/blob/2.x/composer.json) to v2.1.5. I'm wondering how it would have been updated. Is boostrap4 in your site's composer.json? Did you maybe specifically run something like `composer update drupal/bootstrap4`? 

From what I've seen, the versionless way to include Bootstrap4's SCSS is instead use:

`[DOCROOT]/themes/contrib/bootstrap4/scss/style`

However, in my limited testing, using that versionless SCSS file causes issues with our theme because there's a bit of extra stuff that gets included. 

Like Bill said, we'll need to get together and decide the best path forward at some point. If we can pull it off, removing bootstrap entirely would probably be the most future-proof.

**Comment by amyliles** [comment]
I wondered about that too.  It looks like Bootstrap4 updated to 4.6 in this release;
https://www.drupal.org/project/bootstrap4/releases/2.1.5

If you check the main project page for Bootstrap4, they actually also list 4.6.1 in the description now.  https://www.drupal.org/project/bootstrap4/

**Comment by amyliles** [comment]
And I only ran the standard updates, nothing specific to Bootstrap4  :)

**Comment by amyliles** [comment]
I should also mention, the only items that were broken were simply caused by the 'missing' file, so changing the version in the path worked fine.  Using the updated version of Bootstrap (4.6.1) seems to have no other impact on the site functionality, at least so far.

**Comment by trubach** [comment]
This should be fixed when #843 is pushed and merged.
