### ISSUE TITLE
h1 margin with breadcrumbs

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#815]
We override the H1 on the template with side navigation, but not without.

Override it on the page-content-page.html.twig file please

![Screen Shot 2022-08-12 at 3 11 18 PM](https://user-images.githubusercontent.com/54747669/184436815-0f4aa30b-8f97-4f75-8bb9-cea1c0a16af8.png)

**Comment by wrg20** [comment]
![Image](https://user-images.githubusercontent.com/1544079/184933742-fddcd4b2-caab-4f2e-8138-f7aa2ec6870f.png)

**Comment by mwllr** [comment]
still missing 10px of padding on the pages without side nav.
https://illinois-drupal.web.illinois.edu/academics/nres-undergraduate-degree
https://illinois-drupal.web.illinois.edu/academics - no side nav needs padding added

**Comment by wrg20** [comment]
@mwllr 

So currently the padding above is only 28px instead of 40px like our sidenav version of the page.  Do you remember if there was a reason for this?


![Image](https://user-images.githubusercontent.com/1544079/206773572-5fd11cef-f3d5-4cec-b726-05a9a491748d.png)

This picture ^ shows the same amount of padding as our sidebar version.  40px above versus the 28px that is currently the top padding for a page without sidenav

**Comment by wrg20** [comment]
Added 10px of padding to the bottom of the breadcrumb to match the style of the breadcrumb on the page with side navigation.  This is only applied at the 992px wide or larger viewport.  Below 992px the bottom padding is reduced to 0px.  If you would like the viewports at smaller sizes to have more padding below the breadcrumb please let me know.
