### ISSUE TITLE
Update the Bootstrap version from 4.6.1 to 5.2.0

### ISSUE THREAD

**Issue by jasonpfrye** [ATLAS-Illinois/Illinois-Framework-Theme#843]
The documentation outlines the changes between v4 and v5: https://getbootstrap.com/docs/5.0/migration/

Of note, v5 would no longer provide support for some older browser versions, deprecate a few mixins that are being used, and alter a few things about the framework that may impact our implementation, like the use of the breakpoint mixins.

**Comment by trubach** [comment]
Hey @jasonpfrye - this might be a good opportunity to change how we're importing the bootstrap SASS into our theme. In line 4 of ./scss/style.scss it is currently:

`@import '../../../../themes/contrib/bootstrap5/dist/bootstrap/5.2.0/scss/bootstrap';`

My impression is that the bootstrap Drupal theme wants you to import bootstrap using its style.scss instead, so that line four should be:

`@import '../../../../themes/contrib/bootstrap5/scss/style.scss';`

The issue with the way we've been doing it is that we're tied to a particular version of the Drupal bootstrap theme. If we use their style.scss, we can update the theme without worrying about that import breaking.

The downside is that I'm not sure if using the style.scss will bring in extra cruft that might cause a bigger headache than it's worth.

If you'd rather punt the issue for now, that's OK, but I thought I'd suggest it since you're working on it. Thanks for your help!

**Comment by jasonpfrye** [comment]
Thanks, @trubach. I think that's a good solution. I ran into a compile error yesterday after updating the bootstrap theme that pulled in a minor version update. I'll see if pointing to the style.scss presents any problems. 

I'm not 100% sure how to handle the new Bootstrap5 theme requirement. I've made the required change in the composer file, but it likely needs to be updated in the other repo as well. I also receive an error if the Bootstrap5 theme hasn't been installed prior to loading in the framework theme update.

**Comment by trubach** [comment]
Instead of replacing bootstrap4 with bootstrap5 in the composer file, I think it'd be better to have both. Then, I think we can create a theme update hook to install the bootstrap5 theme and (maybe) uninstall the bootstrap4 theme.

If everything works like it hopefully should, when we update our sites, the process should be running `composer update` to get the bootstrap5 theme, and then running `drush updb` to install the new theme. I'm sure I'm overlooking something though. :)

**Comment by jasonpfrye** [comment]
That should work. I'll put bootstrap4 back in the composer.json file. Thanks for the help! Still working through some issues with the update, but should be in a good spot to test soon.
