### ISSUE TITLE
page /news -align breadcrumb/title next to side nav

### ISSUE THREAD

**Issue by mwllr** [ATLAS-Illinois/Illinois-Framework-Theme#868]
currently showing on top of side nav, should go on right of side nav like rest of pages. Will do that for the entire section.
![Screen Shot 2022-11-15 at 11 58 35 AM](https://user-images.githubusercontent.com/54747669/201992717-1f66cbe7-a50c-4833-8f84-838cd25c209e.png)

Should look like: 
![Screen Shot 2022-11-15 at 12 00 50 PM](https://user-images.githubusercontent.com/54747669/201992783-1731fb26-009a-448c-bf4a-d88e94bf7394.png)

**Comment by magjarvis** [comment]
@mwllr @wrg20 check your Page Title block machine names. We had the same issue on MCB and it turns out our subtheme was overriding the illinois_framework_theme_page_title block name. I deleted and recreated the Page Title using the correct machine name (illinois_framework_theme_page_title) and that worked for us.
