### ISSUE TITLE
Spotlight Family - Feature Block

### ISSUE THREAD

**Issue by nbaxley-uiuc** [ATLAS-Illinois/Illinois-Framework-Theme#93]
- [x] Add a "Read full story" that links to the detail page
- [x] Make the title and image link to the detail page
- [x] Constrain the width of the presentation to the page width

![image](https://user-images.githubusercontent.com/62560479/118194124-7fb45a80-b40e-11eb-90da-5e445ed3b42e.png)
https://app.zeplin.io/project/6083082b532b4d1e0f670e65/screen/609d9e9175d3535df1316535

**Comment by nbaxley-uiuc** [comment]
Create this as a view block that shows the most recent item tagged as sticky.

**Comment by nbaxley-uiuc** [comment]
I have an instance of this on the main page of drupal.webtheme.  I need @mwllr to weigh in on this, but to my mind we need to have the width on this contained to the template width and we need to have a "Read full story" button added to send people to the detail page.

**Comment by robgasc** [comment]
@nbaxley-uiuc So, for the link, right now the more details field when filled creates an orange button. The title/image are not linked, currently, because the more details could theoretically be unrelated to the title/image. If there is no more details, should we default to linking to the spotlight?

I also have no qualms about making the width fixed-width instead of full-width. The full-width is the current design. So I'm not sure. Any more clarity would be cool.

**Comment by nbaxley-uiuc** [comment]
1) For the more details button.  I see where your coming from, but my understanding was that the more details is additional reading beyond the content of the spotlight.  So it should be listed as a link at the bottom of the article page.  Anywhere else the spotlight item is listed it should be directing the user to the full article, so the title and the read more button are taking them to the article detail page (the node).
2) Full width.  If you look at the sandbox page (https://drupal-sandbox.webtheme.illinois.edu/) you can see that the content is spreading beyond the page width.  The background treatment looks correct, but the content (title, summary, image) should be contained in the width.

**Comment by robgasc** [comment]
The branch is merged, closing this issue. :)
